// Code generated by sparkle.

package exchange

//func (u *User) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (b *Bundle) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (f *Factory) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (h *HourData) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (d *DayData) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (t *Token) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (t *TokenHourData) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (t *TokenDayData) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (p *Pair) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (p *PairHourData) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (p *PairDayData) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (l *LiquidityPosition) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (l *LiquidityPositionSnapshot) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (t *Transaction) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (m *Mint) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (b *Burn) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (s *Swap) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}
