package exchange

import (
	pbcodec "github.com/streamingfast/sparkle/pb/dfuse/ethereum/codec/v1"
)

func (s *Subgraph) HandlePairSyncEvent(ev *PairSyncEvent) error {
	panic("code skeleton generated by sparkle. implement me")
}
